### ISSUE TITLE
how to change the role of user from flutter app

### ISSUE THREAD

**Issue by faisalmushtaq007** [GetStream/stream-chat-flutter#1120]
I tried to use partialUpdateUser but i am getting error
Unhandled Exception: StreamChatNetworkError(code: 17, message: UpdateUsersPartial failed with error: "User '6257c084393f3763dbba7f99' with role 'user' is not allowed to perform action UpdateUserRole", statusCode: 403, data: ErrorResponse(code: 17, message: UpdateUsersPartial failed with error: "User '6257c084393f3763dbba7f99' with role 'user' is not allowed to perform action UpdateUserRole", statusCode: 403, moreInfo: https://getstream.io/chat/docs/api_errors_response)).
Please help me with correct way

**Comment by imtoori** [comment]
This is clearly a permission issue
Please check this section of the documentation https://getstream.io/chat/docs/flutter-dart/user_permissions/?language=dart

**Comment by bhanuU25** [comment]
@imtoori can you provide code snippet for assigning or updating a channel Role.

I can only see javascript code snippet and i tried to go through the channel's method but couldn't find any method to update the channel!

if possible can you migrate previous role to current permission/role managment because the exisiting channel admin will lose their permission and will take lot of manual work to assign role from console to do so!

**Comment by imtoori** [comment]
hey @bhanuU25 can you share a link to the js doc you're referring to?

**Comment by bhanuU25** [comment]
@imtoori 
https://getstream.io/chat/docs/flutter-dart/user_permissions/?language=dart&q=role#:~:text=In%20order%20to%20change%20channel%2Dlevel%20role%20of%20the%20user%2C
