### ISSUE TITLE
 `StreamMessageInput` could take a `List<User> usersToMention` parameter

### ISSUE THREAD

**Issue by ValentinVignal** [GetStream/stream-chat-flutter#1177]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

I would like to have dynamic rules on when a user can be mentioned or not in a channel.

A way to do it would be to add the ability to specify by hand the users that can be mentioned.

### Describe the solution that you'd like

It would be nice to have a parameter (for example `usersToMention`) so I can write:

```dart
StreamMessageInput(
  usersToMention: [
    User(/* ... */),
    User(/* ... */),
    User(/* ... */),
  ],
),
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayush221b** [comment]
HI @ValentinVignal thank you so much for reaching out and taking the effort to open a pull request. We were discussing this internally and I think the solution propose is very specific to this particular use case. We are working on ways to address the problem in a generic way so that it can be implemented at an SDK level. We have included this issue in our current sprint and we will keep you in the loop on whatever we discuss.

cc: @imtoori

**Comment by imtoori** [comment]
+1 on that, I think the best solution would be to let you pass a filter that we can apply to the call that we use to fetch the users
it shouldn't be too hard to implement

**Comment by imtoori** [comment]
closing this in favor of #1203
