### ISSUE TITLE
Issues while building the app

### ISSUE THREAD

**Issue by vasilich6107** [GetStream/stream-chat-flutter#1372]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Android

### What version are you using?

latest

### What happened?

Running Gradle task 'bundleRelease'...                          

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':desktop_drop' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

### Steps to reproduce

```bash
switch android gradle plugin to v7.3.1 and try to release the app
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment]
hey @vasilich6107 
Apparently this is due to a dependency
Switching to a less recent gradle plugin should work, can you try that?

**Comment by CalHoll** [comment]
This is holding up a deployment which would fix crashes in production.

I found my way here after my build started failing, it's based on your "desktop_drop" dependency.

Oddly it seems that the issue is because "desktop_drop" has "kotlin-gradle-plugin:1.3.50" stated in the example folder, I'm not sure how this works.

I'm not very familiar with gradle so I've been poking around in the dark to try to figure out what is causing a bunch of crashes on production. I've discovered I need to get my deps upgraded to the latest to fix the issues but there's conflicts, here's a summary of my configuration:

andoid/app/build.gradle:
```
...
     compileSdkVersion 33
...

 dependencies {
         coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
...
}
```

android/build.gradle:
```
buildscript {
    ext.kotlin_version = '1.7.20'
    repositories {
        google() 
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

Here's some of the stack trace related to the build failure:
```
[ +104 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[        ] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
[        ] The following dependencies do not satisfy the required version:
[        ] project ':desktop_drop' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
...
[        ] * Exception is:
[        ] com.android.builder.errors.EvalIssueException: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
[        ] The following dependencies do not satisfy the required version:
[        ] project ':desktop_drop' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
[        ] 	at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt:110)
[        ] 	at com.android.builder.errors.IssueReporter.reportError$default(IssueReporter.kt:106)
```

**Comment by CalHoll** [comment]
I've created a PR on their repo but I'm not sure it's being actively maintained. Is it possible you create a fork and depend on that?
