### ISSUE TITLE
Custom size image in share link template

### ISSUE THREAD

**Issue by tanphuccgl** [GetStream/stream-chat-flutter#1400]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web

### Describe the solution that you'd like

I want custom image size in share link. I would be very happy if you could help me with that.

### Describe alternatives that you have considered

Can you help me customize it?

<img width="703" alt="Screen Shot 2022-12-08 at 00 27 44" src="https://user-images.githubusercontent.com/80146701/206248891-af2e5d56-fef5-4f5c-a185-70bd992b4b85.png">

### Additional context

<img width=30% alt="Screen Shot 2022-12-08 at 00 27 44" src="https://user-images.githubusercontent.com/80146701/206249197-1a6ddd30-a136-40df-b816-2e4271cc49bf.jpeg">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hi @tanphuccgl, the images are auto-sizable. We do this way because custom sizes would crop the image when they are too wide or too tall. Our logic sizes the image in to keep its proportion and not crop it either. 

When the image it big, it takes the whole width allowed to a message and we calculate the height respecting the aspect ratio. When the image is not very big, it doesn't take the whole width and we draw the image accordingly with its dimensions. 

When don't allow a fixed size for the image, because any size you choose will be bad for one image or another.

**Comment by tanphuccgl** [comment]
i get it. thank you @leandroBorgesFerreira
