### ISSUE TITLE
Thread Reply Count includes count of deleted thread reply as well!

### ISSUE THREAD

**Issue by bhanuU25** [GetStream/stream-chat-flutter#1409]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^5.1.0

### What happened?

The count of thread replies includes deleted thread replies as well!
I mentioned this bug but it was closed because it was a backend issue!

How can I inform the backend team about this to be resolved?

### Steps to reproduce

```bash
1. Thread Replies on a message.
2. Delete some of those replies in the thread.
3. The count of thread replies stays the same and includes the count of deleted replies as well which then confuses users!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leandroBorgesFerreira** [comment]
Hello @bhanuU25. We count messages in thread **when soft deleted**, but we don't **when hard deleted**. This is a product decision, because some users can choose to show messages as "_message deleted_". 

If you want to hide the delete messages and keep the correct thread replies count. I suggest you to use hard delete, instead of soft deleting your messages.
