### ISSUE TITLE
queryChannels() method returns Stream?

### ISSUE THREAD

**Issue by Elevencode** [GetStream/stream-chat-flutter#1609]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

stream_chat: ^6.3.0

### What happened?

On a backend written in Dart, I get a list of all channels and then call channel.watch() on each channel. When adding a new channel from the client application, the new channel is not included in this stream. Am I doing something wrong?

code on backend:

```
Stream<List<Channel>> channels = client.queryChannels(filter: Filter.in_('type', ['team']));


  channels.listen((channelList) async {
    for (final channel in channelList) {
      final body = jsonEncode({
        ...
      });
      final response = await http.post(
       ...
      );

      channel.watch();
    }
  });
```

### Steps to reproduce

```bash
check my code
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment]
Hey @Elevencode, `queryChannels` does not watch or handle any changes in the channel list, Its return type is `Stream` because it first tries to fetch channels from local persistence if available and then updates the list again once received from the api.

In order to achieve what you are trying to do, You can instead use the [ChannelListController](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter_core/lib/src/stream_channel_list_controller.dart) and add listeners to get the latest value.

Thanks.

**Comment by Elevencode** [comment]
Hey @xsahil03x ! Thank you!
