### ISSUE TITLE
Message text partial search

### ISSUE THREAD

**Issue by vasilich6107** [GetStream/stream-chat-flutter#1794]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^6.9.0

### What happened?

Hi.

I have a message in my chat `abcdefghijklmnop`.
Im building a search widget but the search api does not allow to partially match the message text. 

It responds with some search results only if one word from my input matches the word in message text.

When I try to search `abcd` it returns the empty result.
Only when I have whole word match `abcdefghijklmnop` it returns non empty response.

here is a request that goes to server.

https://chat.stream-io-api.com/search?api_key=[MY_KEY]&payload={"filter_conditions":{"$and":[{"team":{"$eq":[MY_TEAM_ID]}},{"members":{"$in":[SOME_MEMBER_ID]}}]},"sort":[{"field":"created_at","direction":-1}],"message_filter_conditions":{"text":{"$q":"abcdefg"}},"limit":15}&user_id=[USER_ID]&connection_id=[CONNECTION_ID]

It starts working somehow if I use `$autocomplete` but it is not an option cause I need to search a part of word inside a message but `$autocomplete` only searches like `startsWith`

### Steps to reproduce

```bash
Create `StreamMessageSearchListController` and try to search by part of the word.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @vasilich6107 ,

Thank you for opening this issue with us, as stated in our [documentation](https://getstream.io/chat/docs/flutter-dart/search/?language=dart&q=search#query-parameters) `query` performs a full-text search and not a fuzzy search.

It is like this by design, and also clearly documented, so it is not a `bug`. It is not likely that we will support fuzzy search in the near future, so I am going to close this and will re-open if for some reason it get's prioritized.

**Comment by anhdo9797** [comment]
same issue
