### ISSUE TITLE
Deprecated Member Use

### ISSUE THREAD

**Issue by EkundayoPashione** [GetStream/stream-chat-flutter#1825]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^7.0.1

### What happened?

When trying to archive, I found that the Photo Manager package has an issue and the solution is to switch to it's pre-release version

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Relevant log output

```shell
error: ../../.pub-cache/hosted/pub.dev/photo_manager-2.8.1/lib/src/internal/image_provider.dart:71:5: Error: Type 'DecoderCallback' not found.
    DecoderCallback decode, // ignore: deprecated_member_use
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashanftw** [comment]
@EkundayoPashione im facing the issue on  flutter version 3.16.7. however i was able to temporary solve the issue by adding below lines to pubspec.yaml file. Please update the stream_chat_flutter package to slove this issue. 

dependency_overrides:
  photo_manager: ^3.0.0-dev.2

**Comment by EkundayoPashione** [comment]
Thank you, I'll try it

**Comment by esarbanis** [comment]
Hi guys, we are aware about this issue, there is a fix in `photo_manager` but unfortunately it is `beta` release and we do not want to depend on a `pre-release` version in our stable one. So, we currently support flutter `3.13.x` in our stable release and `3.16.x` in our `beta`. If it is an absolute necessity to use flutter `3.16.x` you _could_ switch to our `beta`, BUT it is an unstable release. Otherwise, set your flutter version to `3.13.x` 🙏 .

We are closely monitory `photo_manager`'s releases and we will publish a release as soon as they publish their `v3`.
