### ISSUE TITLE
Floating date divider overlap

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1917]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS, Android, Web, Windows, MacOS, Linux

### Is your feature request related to a problem?

Floating date divider is overlapping with other date dividers on scroll, can this be improved?

<img width="324" alt="image" src="https://github.com/GetStream/stream-chat-flutter/assets/16155640/9dc8a810-43d9-4618-8995-c180fd6e6148">

### Describe the solution that you'd like

Would be great to have a smoother experience, eg like on the example below, previous divider just moves away and they don't overlap

https://github.com/GetStream/stream-chat-flutter/assets/16155640/931ba9a4-3c6f-4a2d-a4ea-e2bdc5895407

### Describe alternatives that you have considered

Even `sticky_headers` package has a better UI

![image](https://raw.githubusercontent.com/letsar/flutter_sticky_header/master/doc/images/sticky_header_all.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment]
Hi @geweald ,

The floating date divider is overlapping in order to be swapped as demonstrated below. 

https://github.com/GetStream/stream-chat-flutter/assets/633903/a6ac3718-f47a-467d-ac00-8664272ca462

If you wish to customize the divider you can, by overriding `StreamMessageListView.dateDividerBuilder`
