### ISSUE TITLE
Update old dependencies

### ISSUE THREAD

**Issue by flodaniel** [GetStream/stream-chat-flutter#2003]
### Which packages are you using?

stream_chat, stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android, Web, Windows, MacOS, Linux

### What version are you using?

8

### What happened?

Some dependencies where updated in version 8 but not all of them, which makes using and working with stream chat more and more annoying. Can we please get frequent updates to ensure the packages can work with the latest versions of other packages? Some of them are:

- rxdart
- share_plus
- synchronized

### Steps to reproduce

```bash
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi @flodaniel, 

While I do agree we need to be a bit more proactive in upgrading our deps, we try to make sure we support as many as users as possible. Updating all dependencies at once often can leave many users unable to use their projects so we have to consider which ones are worth updating since we try to support the nth and n-1th version of Flutter.

As an example, the latest version of `synchronized` would restrict the package to Dart 3.5 which would support only one Flutter version and remove support for all else. A similar issue exists with the latest version of share_plus but likely not as bad. 

So we will try to update these as soon as possible but we need to analyse which ones we can considering Flutter 3.24 as well. We are also expanding our Flutter team so expect these to be done more often soon. 

Thanks!

**Comment by mauriziopinotti** [comment]
Upgrading share_plus is utterly important as version 10.x bumps web dependency to 1.0, that most of the packages are now requiring.

**Comment by deven98** [comment]
@mauriziopinotti we just merged the updates and the new release should be out in a bit.
