### ISSUE TITLE
Transition to ChannelPage when using Customize Channel Preview

### ISSUE THREAD

**Issue by koishi** [GetStream/stream-chat-flutter#206]
I refer to tutorials and example code.
- https://getstream.io/chat/flutter/tutorial/
- https://github.com/GetStream/stream-chat-flutter/blob/master/example/lib/customize_channel_preview.dart

I have a question about customizing the channelPreview using channelPreviewBuilder in ChannelListPage.

How should I implement the transition to the ChannelPage?
In the current tutorial and example code, tapping the list does not transition to the ChannelPage.

gz#8556

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8556'>Zendesk ticket #8556</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and get back to you soon.

Cheers
Stream Team

**Comment by Nash0x7E2** [comment]
Hi @koishi! Thank you for bringing this up. I had a look at the code and made a change. 

In `_channelPreviewBuilder`, you can implement `onTap` then call the navigator to push a new route. In this case, we can use `MaterialPageRoute` to push a new instance of `ChannelPage`.  

Since `ChannelPage` relies on an inherited widget for obtaining the current channel, we wrap the page using a `StreamChannel` passing the current channel. 

You are free to use any PageRoute. I am only using `MaterialPageRoute` for simplicity. The code below also works with `CupertinoPageRoute` 😄 .


```dart
  Widget _channelPreviewBuilder(BuildContext context, Channel channel) {
    final lastMessage = channel.state.messages.reversed
        .firstWhere((message) => !message.isDeleted);

    final subtitle = (lastMessage == null ? "nothing yet" : lastMessage.text);
    final opacity = channel.state.unreadCount > .0 ? 1.0 : 0.5;

    return ListTile(
      key: ValueKey<String>(channel.cid),
      onTap: () {
        Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => StreamChannel(
              child: ChannelPage(),
              channel: channel,
            ),
          ),
        );
      },
...
```

I hope this helps, 
Nash
