### ISSUE TITLE
Version solving failed after upgrading firebase dependencies [Tracking #330]

### ISSUE THREAD

**Issue by luvishq** [GetStream/stream-chat-flutter#344]
Adding so that we can track it here [Version solving failed](https://github.com/GetStream/stream-chat-flutter/issues/330)

**Important** : Blocking firebase auth updates which fixes auth related issue and are being blocked because of stream chat version issue.

gz#10300

**Comment by xsahil03x** [comment]
@luvishq it's not really related to our package. It's due to `dio` (which we use internally for making network calls) using an earlier version of `http_parser`. One thing you can try doing is to override the `dio` package to `dio: ^4.0.0-prev1` as it contains the latest version of `http_parser`. We are not updating it in our package because it's not yet in the stable release.

**Comment by luvishq** [comment]
@xsahil03x : I tried this solution but it didn't work and I am getting the same error, can you please share a solution which is working at your end with the updated firebase dependencies. I see the `dio` is in prev-3 right now, so should be stable soon, can you try to get this fixed as they update it and also it would be great if you can share a solution for the time.

**Comment by xsahil03x** [comment]
Hey, I tried overriding versions and the pub get worked fine. Can you share with me the piece of code which is throwing that particular error?

**Comment by luvishq** [comment]
@xsahil03x : It seems we were using an older version of stream and the current one changed the implementation instead of Client it is now StreamClient, we confirmed from the docs, thanks though :)

**Comment by xsahil03x** [comment]
Nice, closing this issue then. Feel free to open if the issue reappears. 😄
