### ISSUE TITLE
Pasting images or files from clipboard into message input does not work

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#395]
Right now it is not possible to paste copied images or files in to the message input, which is a ubiquitous feature on imessage, slack, etc and one that our users expect

**Comment by imtoori** [comment]
Apparently, this is not supported by Flutter itself https://github.com/flutter/flutter/issues/20796
I tried using a workaround, as you can see in my PR, but we don't think this is something we should publish.
I'll close this issue since there's nothing we can do, let me know what you think about it and if you have any ideas
