### ISSUE TITLE
Giphy Changes

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#435]
Is there any way to make changes to how giphy is used?
Like for example how Facebook allows you to search and a list of gifs are returned vs just a random one? I know it can be done if you make it yourself but would be nice to add a flag to have the random way or a way like Facebook.

**Comment by imtoori** [comment]
Hi and thanks for the feature request

We don't provide this kind of integration out of the box and it's not one of our priorities at the moment
The only solution is to do it yourself

I can suggest you some nice packages like this one https://pub.dev/packages/giphy_picker

I'll add this feature request to our backlog so that we'll do it eventually

**Comment by imtoori** [comment]
hey @rlee1990 
I don't think we'll ever add this directly to the sdk, but we're planning to write a blogpost about this :) 
so stay tuned :D
