### ISSUE TITLE
Date Display Issue

### ISSUE THREAD

**Issue by rlee1990** [GetStream/stream-chat-flutter#519]
**Describe the bug**
When you scroll the data in the center never disappears and also overlaps the other dates and creates a bad look.

**What package are you using? What version?**
Running on lastest dev version. Seen the issue on stable.

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
Create a channel and add enough messages to scroll.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/21372502/124185098-81061900-da88-11eb-9524-bfc75df19e43.jpeg)

![image](https://user-images.githubusercontent.com/21372502/124185105-85323680-da88-11eb-938f-b5c862fed5cf.jpeg)

**Comment by imtoori** [comment]
the idea is to have something like whatsapp
the floating timestamp refers the messages in the bottom and it should hide once you reach another date

hope I'm clear 😅 

do you see any strange behaviour that doesn't reflect this?

**Comment by rlee1990** [comment]
@imtoori Well in the image the dates overlap when scrolling shouldn't the bottom one fade and disappear? If so that is not happening then both just stay there

**Comment by imtoori** [comment]
Sometimes that happens because there are some tricks to make it work, mostly due to the MessageListView
But we'll work on a completely custom MessageListView in the next months that should make this better and have even better performance overall
Keep in mind that you can always disable the floating timestamps using `MessageListView.showFloatingDateDivider: false`
Thanks for the feedback!
