### ISSUE TITLE
Kept chat history, even after member leaving the channel

### ISSUE THREAD

**Issue by hz081** [GetStream/stream-chat-flutter#579]
I have a question. How can I kept the chat history of the channel from all of channel members, even if that member was not in the channel anymore.

Example: member leaving the channel, but chat history (before member leaving the channel) remain. And user still can see the history of the chat.

Thanks

**Comment by shodgetts** [comment]
Hello, thanks for the feature request, but this is not currently supported and we can't realistically support this due to constraints on our backend. It would probably require multiple replications of the channel data, which we aren't willing able to do at scale, n number of times, for this feature.
