### ISSUE TITLE
one to one channel example

### ISSUE THREAD

**Issue by brizaldi** [GetStream/stream-chat-flutter#7]
is there an example about how to initiate one to one conversation?

i got error like this when i call `await channel.watch();`

`E/flutter (19258): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ApiError{body: Not Found, jsonData: null, status: 404, code: null}`

**Comment by imtoori** [comment]
Hi and thank you for the reporting

There was an error initializing the channel without an id.
The url was wrong and the response was always 404.

With [stream_chat_dart](https://github.com/GetStream/stream-chat-dart/pull/15) version 0.1.20 the bug is fixed.

To create a channel follow the docs [here](https://getstream.io/chat/docs/channel_conversations/?language=dart), so run `flutter pub get` to get the latest version


The result should be something like this
```dart

  final channel = client.channel('messaging', extraData: {
    'members': [
      'thierry',
      'tommaso',
    ],
  });

  await channel.create();
  channel.watch();

```

**Comment by brizaldi** [comment]
can you also update [stream_chat_flutter](https://pub.dev/packages/stream_chat_flutter) ?

**Comment by imtoori** [comment]
Actually It's not necessary to do so
Just run `flutter packages upgrade` and rebuild your app
