### ISSUE TITLE
project ':video_compress' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31

### ISSUE THREAD

**Issue by omuniverse** [GetStream/stream-chat-flutter#738]
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

3.1.1

### What happened?

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':video_compress' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vbuberen** [comment]
@imtoori Would like to reopen this issue, because the problem is with one of Stream SDK dependencies `video_compress`, not with the original reporter's code. 
Seems like the author of this dependency hasn't released new versions for quite some time, so people point to `master` branch to avoid build problems: https://github.com/jonataslaw/VideoCompress/issues/142

**Comment by vbuberen** [comment]
From my side I can confirm that with `stream_chat_flutter: ^3.3.2` dependency I can't build my Flutter project for Android device/emulator in the latest Android Studio (Arctic Fox | 2020.3.1 Patch 4)

**Comment by vbuberen** [comment]
@imtoori Sorry for bothering, but maybe you haven't seem previous comments ☝🏻 

I tried to add a PR to update that `video_compress` package (https://github.com/jonataslaw/VideoCompress/pull/153) but still got no response from the author of that library.

Anyway, it might be useful to use the workaround on pointing to `master` in Stream SDK till we get a new release of that dependency.

**Comment by imtoori** [comment]
@vbuberen I'll reopen the issue
The thing is we can't point to `master` because it's not possible to publish a package with a git dependency, so we have to wait for a new release, or try another solution.

**Comment by sachaarbonel** [comment]
Hey guys, I think I had this bug and I managed to solve it with a combination of fixes (I'm on M1)
1. First I updated android studio to the latest version ( 2021.3.1 Canary 3)
2. I installed the latest versions of SDK tools in Preferences > Appearance & Behavior > Android SDK
3. Then I ran flutter doctor and realized it couldn't detect the proper bundled java version
4. I installed [sdkman](https://sdkman.io/install) which is a package manager
5. I installed the JDK with sdkman: `sdk install java 17.0.2-oracle`
6. I followed those instructions: [here](https://stackoverflow.com/a/68575967/14094532)
7. I installed kotlin version 1.6.0 with sdkman: `sdk install kotlin 1.6.0`
8. I modified in my flutter app in `android/build.gradle`: 
```build.gradle
buildscript {
    ext.kotlin_version = '1.6.0'
    ...
```
9.Then FINALLY added to `android/app/build.gradle`
```build.gradle
    defaultConfig {
        multiDexEnabled true
        ...
    }
```

**Comment by vbuberen** [comment]
Thanks, but steps you described have nothing to do with the issue, since it is not about config of the app where `stream_chat_flutter` is used, but about specific dependency called `video_compress`, which still relies on old Kotlin version. Provided logs clearly mention the reason of the issue.

The project where I had issue (and which I left in January) had all the latest Kotlin and Android Gradle plugin versions back then (1.6.10 and 7.0.4 respectively) as well as minSDK 21.

Unfortunately, maintainer of that library doesn't care about users reporting the issue or PRs, like the one I created.
