### ISSUE TITLE
upgrading persistence - lost data

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-flutter#748]
hi,
already had this behaviour before.
i upgraded yesterday chat + persistence plugin.
on first launch, some of my messages have lost their user (user == null)

is it because i upgrade persistence plugin ?
i reinstall app to be sure => same behaviour.

i run some nodejs script to get messages, and evzrything is fine.

is it possible to reset local database to wipe out data and start fresh ?

ios
last version of pubspec

thank you,
Nelson

**Comment by imtoori** [comment]
hey @Abacaxi-Nelson did you find anything?
can you try with the latest release?

**Comment by Abacaxi-Nelson** [comment]
Hey,
i just remove persistence for now.
yeah i will have a look !
next week, cause we are pushing an important version this week :)

Thank you @imtoori

**Comment by fbardecio** [comment]
Hey @imtoori! I'm having the same exact behavior while using `stream_chat_persistence 3.0.0` and `stream_chat_flutter 3.3.2`.
The first time that the chat renders messages, it does it as expected, but then, somehow, the same messages are rendered again, and some of them have the user as `null`.

Chat throws two exceptions:
`Null check operator used on a null value` and `type 'UniqueKey' is not a subtype of type 'IndexedKey' in type cast`

I can give you some more info:

- Both errors persist if we clean the cache or uninstall and install the app again.
- Every message that comes with a null user, has an existing user in the DB.
- Everything works as expected if we remove the `stream_chat_persistence 3.0.0` package.
- I've used the `messageFilter` param in the `MessagesListView` widget, to filter those messages whose have a null user, after doing this, I've seen that all the messages that come with a null user, were sent from the same user. This user is a "super" user named System, which takes care of sending different system messages across the channels.

It is possible that the app is somehow not saving this user data in his messages in the local database, and somehow it explodes when trying to get them from there? I'm assuming that the issue is in the local DB since as I said, the messages in the online Explorer are displaying the user data, and removing the `stream_chat_persistence 3.0.0` fixes the issue 🤔 

Please let me know if you have any question

**Comment by imtoori** [comment]
hey @fbardecio thanks for all the useful information
I'm struggling with reproducing what you wrote 🤔 

Could you email support, so that we can ask for your app id and key and verify if we manage to reproduce the error?
Thanks!

**Comment by Abacaxi-Nelson** [comment]
Hey
@fbardecio keep me updated :)
I turn off persistence because of this

**Comment by geweald** [comment]
I'm having the same issue (on web, haven't checked mobile yet), everything works without cache, tho when reading from cache then some messages have null user and getting the error in lines where `message.user!` is used inside the library

**Comment by fbardecio** [comment]
I have tried to reproduce the error in a separate project with only stream chat flutter and stream chat persistence packages, but everything was working as expected, I will try again when I have some free time and I will update you guys.

**Comment by fbardecio** [comment]
Hey @imtoori ! I managed to reproduce the issue in a separate project after adding a bloc package to it and a bloc to load the channels.
It has a dependency override due to chewie being outdated. ([There is an open issue here for updating chewie](https://github.com/GetStream/stream-chat-flutter/issues/805)).

[This is the repository](https://github.com/fbardecio/SChat-test/blob/main/lib/bloc/messages_bloc.dart) where I was able to reproduce the issue.

Again, it is happening when Stream Chat Persistence is enabled and only in some channels with our "super user" messages.
I have also noticed some error logs like the ones specified in [this issue](https://github.com/GetStream/stream-chat-flutter/issues/600).

The project does not have my credentials, but let me know if you want me to provide them in order to access my channels and messages.

**Comment by geweald** [comment]
Hey @imtoori any progress on this? Happens both on mobile and web when reading some channels from cache.

**Comment by xsahil03x** [comment]
Hey @fbardecio, I tried reproducing the issue but failed with my credentials. Can you share your's via a support ticket or on my email: sahil@getstream.io

Thanks,
Sahil

**Comment by fbardecio** [comment]
Hi, @xsahil03x I've sent a ticket to the support team with my credentials. About the issue, we still have stream chat persistence disabled and everything works as expected. It took me a while to reproduce the issue in the separated project, but once you manage to make it throw the exception, it happens every single time, even after clearing the app cache, that's all I can add right now 😅

**Comment by xsahil03x** [comment]
Hey @fbardecio, thanks for the credentials, can you also the app id, please?
